services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://sravanthidasyam0_db_user:pmfNfPjYbxh6UV8N@cluster0.et7dlqh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: